token: "eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhd
Wx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tdHJoNTgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2U
tYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjI1NmNlODU2LWY2NzAtMTFlOC05MmZkLTA4MDAyN
2MxODFlNyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.lwKFi0M66WyKMNr-_yd5N8yX2K8orR8JmnP04JeJOLm9bPv-g0NJBiL8i2P9FsxT_GAx
qy4X269Gq_3fgwMCjh5IFrbDnFXMB8ue8E3wDhRJm6_A9Xp5cO2F0O4UgMPQggnsZpIqLYGJTA_BnG8jGdyjuFDT8U_k18IemhTewRszBjoGffcG1L32rabpzvJ_3t3m5YZvvvzkY1wu1p
s5aY4mBb0XuNvX6KYnuo9qjI4lNFs3TJDvIeS_fhEr4ImxgXopdGF1xZ2p18AGcTGALGcGbFxjOlgd67wLtoYJbrn97LBmc4q25Sh_4TfZ77K97MwUesHVHquMtoStnU7jMA"
cluster_url: "127.0.0.1:8001"
role:
  name: "dev_admin"
  title: developer_access