requirements:
  - namespace: "test1"
    role: "dev_admin"
    user: "vinit"
  - namespace: "test2"
    role: "dev_admin"
    user: "goel"
  - namespace: "test3"
    role: "dev_admin"
    user: "kumar"